[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chatops"
version = "0.3.0"
description = "Command line toolkit for operations teams"
authors = [{name = "Franck Kengne"}]

[project.scripts]
chatops = "chatops.cli:app"

